#!/bin/sh

set -eu

main() {
  validate "$@"

  from=$1
  into=$2

  if ! fast_forwarded > /dev/null 2>&1; then
    echo "The $from branch is not fast-forwarded." >&2
    exit 2
  fi
}

fast_forwarded() {
  if [ "$(git rev-list --count origin/"$from"..origin/"$into")" -eq 0 ]; then
    echo true
    return 0
  else
    echo false
    return 1
  fi
}

validate() {
  if [ "$#" -ne 2 ]; then
    echo "Require two arguments" >&2
    exit 1
  fi
}

main "$@"
