name: "git-flow observer"
description: "git-flow observer allows you to check your project is in correct operation as git-flow"
author: "noraworld"
# branding:
#   icon: search
#   color: green

inputs:
  head:
    description: "The branch name as basis for comparison"
    required: true
  base:
    description: "The branch name that is checked whether or not fast-forwarded"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Git operation
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Observe
      # https://github.com/actions/checkout/issues/296
      run: ${{ github.action_path }}/abcdefg ${{ inputs.head }} ${{ inputs.base }}
      shell: sh
