name: "TBD"
description: "TBD"
author: "noraworld"
#branding:
#  icon: git-branch
#  color: blue

inputs:
  main:
    description: "TBD"
    default: main
    required: false
  develop:
    description: "TBD"
    default: develop
    required: false
  checkbox:
    description: "TBD"
    default: true
    required: false
  title:
    description: "TBD"
    default: false
    required: false
  author:
    description: "TBD"
    default: true
    required: false

runs:
  using: "composite"
  steps:
    - name: Enable Git operation
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: test
      name: test
      run: ${{ github.action_path }}/main
      shell: sh
      env:
        REPOSITORY: ${{ github.repository }}
        MAIN: ${{ inputs.main }}
        DEVELOP: ${{ inputs.develop }}
        CHECKBOX: ${{ inputs.checkbox }}
        TITLE: ${{ inputs.title }}
        AUTHOR: ${{ inputs.author }}
        PR: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ github.token }}
