name: "TBD"
description: "TBD"
author: "noraworld"
#branding:
#  icon: git-branch
#  color: blue

inputs:
  main:
    description: "TBD"
    required: true
  develop:
    description: "TBD"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Git operation
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: test
      name: test
      run: echo "::set-output name=pr::$(${{ github.action_path }}/main ${{ inputs.main }} ${{ inputs.develop }})"
      shell: sh
      env:
        REPOSITORY: ${{ github.repository }}
        MAIN: ${{ inputs.main }}
        DEVELOP: ${{ inputs.develop }}
        PR: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ github.token }}

    # - name: comment
    #   # run: gh pr comment ${{ github.event.number }} --body "${{ steps.test.outputs.pr }}"
    #   run: echo ${{ github.event.number }} and "${{ steps.test.outputs.pr }}"
    #   shell: sh
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
