name: "test"
description: "test"
author: "noraworld"
# branding:
#   icon: search
#   color: green

inputs:
  from:
    description: "TBD"
    required: true
  into:
    description: "TBD"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Git operation
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: check
      # https://github.com/actions/checkout/issues/296
      run: ${{ github.action_path }}/abcdefg ${{ inputs.from }} ${{ inputs.into }}
