name: "TBD"
description: "TBD"
author: "noraworld"
#branding:
#  icon: git-branch
#  color: blue

inputs:
  main:
    description: "TBD"
    required: true
  develop:
    description: "TBD"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Git operation
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: test
      run: ${{ github.action_path }}/main ${{ inputs.main }} ${{ inputs.develop }}
      shell: sh
      env:
        REPOSITORY: ${{ github.repository }}
        MAIN: ${{ inputs.main }}
        DEVELOP: ${{ inputs.develop }}
