#!/bin/bash

set -eu

main() {
  pr_list_json=$(
    # Get merge commits
    git --no-pager log --oneline --reverse --merges origin/"$BASE"..origin/"$HEAD" |

    # Extract merge commit hashes
    awk '{ print $1 }' |

    # Retrieve a JSON from an API
    #
    #   Memo:
    #     Call as many APIs as PRs
    #     I'm not sure how to put all calls together
    xargs -I {} gh api "https://api.github.com/repos/$REPOSITORY/commits/{}/pulls"
  )

  comment
}

comment() {
  if $DEBUG; then
    message
  else
    gh pr comment "$PR" --body "$(message)"
  fi
}

message() {
  paste -d " " <(pr_numbers) <(titles) <(authors) | sed -e "s/^/$(checkboxes)/g"
}

pr_numbers() {
  echo "$pr_list_json" | jq -r .[].number | sed -e 's/^/#/g'
}

titles() {
  if $TITLE; then
    echo "$pr_list_json" | jq -r .[].title
  else
    echo ""
  fi
}

authors() {
  if $AUTHOR; then
    echo "$pr_list_json" | jq -r .[].user.login | sed -e 's/^/@/g'
  else
    echo ""
  fi
}

checkboxes() {
  if $CHECKBOX; then
    echo "* [ ] "
  else
    echo "* "
  fi
}

main "$@"
