#!/bin/bash

set -eu

main() {
  pr_list_json=$(
    # Get merge commits
    git --no-pager log --oneline --reverse --merges origin/"$BASE"..origin/"$HEAD" |

    # Extract merge commit hashes
    awk '{ print $1 }' |

    # Retrieve a JSON from an API
    #
    #   Memo:
    #     Call as many APIs as PRs
    #     I'm not sure how to put all calls together
    xargs -I {} gh api "https://api.github.com/repos/$REPOSITORY/commits/{}/pulls"
  )

  comment
  post_to_slack
}

comment() {
  if $DEBUG; then
    message github
  else
    gh pr comment "$PR" --body "$(message github)"
  fi
}

post_to_slack() {
# Do not indent in this section because extra spaces are interpolated to a Slack message
if $DEBUG; then
slack_message="
The following PRs will be released after <https://github.com/$REPOSITORY/pulls|(DEBUG: a PR number with the link is inserted here on production)> is merged.
$(message slack)
"
else
slack_message="
The following PRs will be released after <https://github.com/$REPOSITORY/pull/$PR|#$PR> is merged.
$(message slack)
"
fi

  if [ "$SLACK_CHANNEL" != "" ] && [ "$SLACK_TOKEN" != "" ]; then
    curl \
      -d "text=$slack_message " \
      -d "channel=$SLACK_CHANNEL" \
      -H "Authorization: Bearer $SLACK_TOKEN" \
      -X POST https://slack.com/api/chat.postMessage
  fi
}

message() {
  type=$1

  paste -d " " <(pr_numbers "$type") <(titles "$type") <(authors "$type") | sed -e "s/^/$(lists "$type")/g"
}

pr_numbers() {
  type=$1

  case $type in
    github)
      echo "$pr_list_json" | jq -r .[].number | sed -e 's/^/#/g'
      ;;
    slack)
      echo "$pr_list_json" | jq -r .[].number | xargs -I {} echo "<https://github.com/$REPOSITORY/pull/{}|#{}>"
      ;;
  esac
}

titles() {
  type=$1

  if $TITLE || [ "$type" = "slack" ]; then
    echo "$pr_list_json" | jq -r .[].title
  else
    echo ""
  fi
}

authors() {
  if ! $AUTHOR; then
    echo ""
    return
  fi

  type=$1

  case $type in
    github)
     echo "$pr_list_json" | jq -r .[].user.login | sed -e 's/^/@/g'
      ;;
    slack)
     echo "$pr_list_json" | jq -r .[].user.login | sed -e 's/^/by `@/g' | sed -e 's/$/`/g'
      ;;
  esac
}

lists() {
  type=$1

  if [ "$type" = "slack" ]; then
    echo "• "
  elif $CHECKBOX; then
    echo "* [ ] "
  else
    echo "* "
  fi
}

main "$@"
