name: "github-pr-release"

on: pull_request

jobs:
  github-pr-release:
    if: startsWith(github.event.pull_request.head.ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: "github-pr-release"
        uses: secondnoraworld/github-actions-sample@develop
        with:
          main: "master"
          develop: "develop"
