name: "github-pr-release"

on:
  pull_request:
    branches:    
      - develop
      - master

jobs:
  github-pr-release:
    runs-on: ubuntu-latest
    steps:
      - name: "github-pr-release"
        run: echo ${{ github.event.pull_request.head.ref }}
        shell: sh
