name: "workflow_test"

on: pull_request

jobs:
  job_test:
    if: github.head_ref != 'master' || github.base_ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: "step_test"
        uses: secondnoraworld/github-actions-sample@develop
        with:
          from: "develop"
          into: "master"
