name: "github-pr-release"

on: pull_request
# on:
#   pull_request:
#     types: [opened]

jobs:
  github-pr-release:
    if: startsWith(github.event.pull_request.head.ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: "github-pr-release"
        uses: secondnoraworld/github-actions-sample@release/20220704-1
        with:
          base: master
          # slack_token: ${{ secrets.SLACK_TOKEN }}
          # slack_channel: ${{ secrets.SLACK_CHANNEL }}
