name: "workflow_test"

on: push

jobs:
  job_test:
    runs-on: ubuntu-latest
    steps:
      - name: "step_test"
        uses: secondnoraworld/github-actions-sample@develop
        with:
          from: "develop"
          into: "master"
